### ISSUE TITLE
Awesome plugin...

### ISSUE THREAD

**Issue by nishal** [treeder/jsqr_flutter#2]
Thanks so much for this plugin! I have been trying to do the same, being a Flutter newbie I haven't had much luck getting this to work for me on my own.

There is just one question I had, I tried a bit of tweeks on your scanner.dart but am unable to get the back camera working on my mobile browsers. Do you know why this might be the case?

Any help will be greatly appreciated!

**Comment by nishal** [comment]
Aplogies, ignore my missing your posted issue #1. Btw, just FYI it works well on iOS too 👍 .

**Comment by treeder** [comment]
Thanks! The back cam works on Android, but having troubles getting it working on iOS. No idea why...

**Comment by nishal** [comment]
I'm unable to get the back camera to work on both Android and iOS. I'm using your example with Scanner, and tried a few variations of constraints to the `getUserMedia` but had no luck with getting the back camera to work both iOS and Android test devices.

Could you check if your example code works with the back camera for Android or if there is something else you're sending in the constraints specifically? When I checked the output of `enumerateDevices` on my Google Pixel XL, I'm able to see two cameras with separate `deviceId's`, but unable to get the back camera to run using the example code both by trying to use `facingMode` or `deviceId` with the camera `deviceId`.

I wonder if you could share any other sample that works for you or if you could get your example to switch between cameras like setup the toggle method to work perhaps?

I found that the code would not work if I was running it on my computer and access from any other address which was not `localhost` for some reason, I get some exceptions show up when checking for `hasCamera` step. This makes it a bit painful because to test from a device as I need to deploy the code to a hosting server for the smallest change, like in my case I'm using Firebase hosting and then remote debug the Pixel to see the console logging etc. I think it might be a CORS issue perhaps and to setup the machines IP as an allowed origin I suppose.

Again, thanks for this amazing code, this is the closest I've gotten in experiments to decide if I should move my entire product codebase from VueJS to Flutter. Until the back camera starts to work, I might have to create a micro site in VueJS just for the part where I need a QR scanner, and then route the rest of the application to Flutter web in a separate folder and communicate via local storage to make the solution work. Feels like this is such a horrible work around just to accomodate a QR scanner with the rest of the Flutter code!

**Comment by treeder** [comment]
Give 0.0.10 a try, this should be fixed now.

**Comment by treeder** [comment]
Let me know if it's not.
