### ISSUE TITLE
Import of package:jsqr/scanner.dart'; returns URI doesn't exists

### ISSUE THREAD

**Issue by emiliano-hc-seguridata** [treeder/jsqr_flutter#4]
Steps followed: 
1. Added dependencie ( jsqr_flutter: ^0.0.1 ) on pubsec
2. Ran flutter pub get, flutter pub upgrade

![imagen](https://user-images.githubusercontent.com/80910026/115418586-3847ff00-a1bf-11eb-8ebb-555aeb45e10c.png)

**Comment by treeder** [comment]
Package for pubspec is `jsqr`, not jsqr_flutter

**Comment by emiliano-hc-seguridata** [comment]
> 
> 
> Package for pubspec is `jsqr`, not jsqr_flutter

Thank you so much! Love your plugin
